import "../css/app.css";
import "../js/menu-toggler";
import "../js/modal";
import "../js/anchor-link-smooth";
import "../js/carousel";
import "../js/accordion";
import "../js/slider";
import "../js/shoppingCart";
import "../js/shippingDetail";